services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chart_ai_dashboard:dev
    container_name: chart_ai_dashboard
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
 