services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jocely_dashboard:dev
    container_name: jocely_dashboard
    ports:
      - "14006:14006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
 